language: elixir

cache:
  directories:
  - priv/plts
  - deps

elixir:
  - 1.9.4

otp_release:
  - 22.0

services:
  - postgresql

before_script:
  - epmd -daemon
  - MIX_ENV=test mix event_store.setup
  - MIX_ENV=jsonb mix event_store.setup

script:
  - mix test.all
  - travis_wait 30 mix dialyzer --halt-exit-status

sudo: required
dist: trusty

addons:
  postgresql: "9.6"
