language: elixir

cache:
  directories:
  - priv/plts
  - deps

elixir:
  - 1.10.2

otp_release:
  - 22.0

services:
  - postgresql

before_script:
  - epmd -daemon
  - MIX_ENV=test mix event_store.setup
  - MIX_ENV=jsonb mix event_store.setup

script:
  - mix format --check-formatted
  - mix test.all
  - travis_wait 30 mix dialyzer

sudo: required
dist: trusty

addons:
  postgresql: "9.6"
