language: elixir

elixir:
  - 1.5.3

otp_release:
  - 20.2

services:
  - postgresql

before_script:
  - epmd -daemon
  - MIX_ENV=test mix event_store.setup
  - MIX_ENV=jsonb mix event_store.setup

script:
  - mix test.all
  - mix dialyzer

sudo: required
dist: trusty

addons:
  postgresql: "9.6"
